### PR TITLE
Removed the protocol

### PR DESCRIPTION
**Pull request by DPG896**
It's sucks lol. It doesnt works in 1.17.30

### CODE REVIEW

**Comment by suerion** [comment]
Ohhh noo it sucks, but you don‘t understand it, how it works! Go ahead and stopp to add pull requests like this. 

Go and learn to understand how rules are working!

**Comment by DPG896** [comment]
Then update it

**Comment by suerion** [comment]
1.1.95 is the latest update, that works with php7, Pocketmine is yet on PHP8. We will update it soon, but we had to do some reworks. With php8 the actuall plugin is broken

**Comment by suerion** [comment]
you could use this one https://github.com/MihaiChirculete/WorldGuard/releases/tag/1.1.95-nopog

**Pull request closed without merging**
